project_id = "myxizupccweukrxfdqmc"

[functions.send-email]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.welcome-email]
verify_jwt = false

[functions.create-invoice]
verify_jwt = true

[functions.process-payment]
verify_jwt = true

[functions.activate-paypal-subscription]
verify_jwt = true

[functions.paypal-webhook-listener]
verify_jwt = false

[functions.cleanup-expired-bookings]
verify_jwt = false