project_id = "myxizupccweukrxfdqmc"

[functions.send-email]
verify_jwt = false

[functions.send-notification-email]
verify_jwt = false

[functions.welcome-email]
verify_jwt = false

[functions.create-invoice]
verify_jwt = true

[functions.process-payment]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.create-paypal-subscription]
verify_jwt = true

[functions.paypal-webhook]
verify_jwt = false